### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ThePenguin1140** [MadJukesInc/WhatTheHellIs.com#2]
Things that I wanna work on, in order of priority.
Add issues for any work done and assign yourself.
- [ ] fix the weird "There was an error querying the server" bug.
- [ ] add a margin or padding at the top of the page (maybe like 30px)
- [ ] add links in the word cloud
- [ ] filter the word cloud to be only verbs and nouns
- [ ] add paths to search queries
- [ ] add images
- [ ] add websters definitions
- [ ] add language support
